### ISSUE TITLE
Put sources in the repository

### ISSUE THREAD

**Issue by Aerath** [Gedd18/WOK#2]
It is pointless to have a binary (.zip) file in a VCS repository. You should probably commit only uncompressed content and release compressed archives.

**Comment by Aerath** [comment]
I understood it, but Git is (almost) only usefull with text content. I was not talking about the sources used in the project template but the sources of the template itself. If you provided the package content directly in the repo it would allow anyone to wade through the history, examine diffs and simply read the files on Github. This is one of the reasons Github has it's release feature, to not bloat the repository with binaries.
Of course this is only my opinion.

**Comment by Gedd18** [comment]
There is no source for the template himself since the template has been generated from the project that i wanted to export as a template. So the first and the only step is "generate from existing model".
But effectively i should use GitHub release feature, so i will do it soon, and later i'll put source code of templated project in the repository. Satisfied  ?.

**Comment by Aerath** [comment]
That was just my two-cents piece of advice. No offense intended
